[workspace]
resolver = "2"
members = [ "wizdraw", "wizdraw-demo-web" ]

# plz use CARGO_PROFILE_RELEASE_DEBUG=true
#
# [profile.release]
# debug = true

[profile.release]
codegen-units = 1
lto = "fat"
